version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules # markup node_modules
      - .:/app #reference

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # markup node_modules
      - .:/app #reference
    command: ["npm", "run", "test"]
